version: '3'
services:
  web:
    volumes:
      - C:\docker\joomla_volume:/var/www/html
    image: joomla
    ports:
      - 830:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_NAME: joomla
  db:
    image: mysql:5.7
    volumes:
      - C:\docker\mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: joomla
      MYSQL_DATABASE: joomla
      MYSQL_PASSWORD: joomla





#docker-compose -f docker-compose-joomla.yml up -d 
#docker-compose -f docker-compose-joomla.yml down
