version: '3'

services:
  db:
    container_name: wp-mysql
    image: mysql:5.7
    volumes:
       - C:\docker\mysql_volume:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - my_net

  wp:
    container_name: wp-web
    volumes:
      - C:\docker\wordpress_volume:/var/www/html
    depends_on:
      - db
    image: wordpress
    ports:
      - 991:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - my_net
networks:
  my_net:


#docker-compose -f docker-compose-wordpress.yml up -d 
#docker-compose -f docker-compose-wordpress.yml down

