version: '3'

services:
  db:
    container_name: ps-mysql
    image: mysql:5.7
    volumes:
       - C:\docker\mysql_volume:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: ps
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps
    ports:
      - "336:3306"
    networks:
      - my_net

  ps:
    container_name: ps-web
    volumes:
      - C:\docker\prestashop_volume:/var/www/html
    #meaning that the db should be created first
    depends_on:
      - db
    image: prestashop/prestashop
    ports:
      - "849:80"
    environment:
      DB_SERVER: db
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
    networks:
      - my_net
networks:
  my_net:



#docker-compose -f docker-compose-prestashop.yml up -d 
#docker-compose logs -f

