FROM centos

COPY fixedfile.sh /fixedfile.sh
RUN chmod +x /fixedfile.sh

CMD /fixedfile.sh


#docker build -t cenas_maradas .
#docker run -d -v "C:\Users\soniad\Documents\docker-from-zero-to-hero\mine\share_volumes\html_files":/opt cenas_maradas
#docker run -d --name nginx -v "C:\Users\soniad\Documents\docker-from-zero-to-hero\mine\share_volumes\html_files":/usr/share/nginx/html -p 811:80 nginx:alpine
